services:
  - type: web
    name: music-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crud-db     # <- nombre de la base que creaste en Render
          property: connectionString
    port: 10000
